server:
  port: 8888
#sentinel 客户端配置
feign:
  sentinel:
    enabled: true
spring:
  profiles:
    active: dev
  application:
    name: security
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    name: security
    type: com.alibaba.druid.pool.DruidDataSource
    #druid配置
    druid:
      #监控统计拦截的filter
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.102.217.76:3306/ATHDB?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&autoReconnectForPools=true&allowMultiQueries=true
      username: spping
      password: '!QAZ@WSX'
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久检查一次，将空闲连接关闭
      time-between-eviction-runs-millis: 60000
      #一个连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'X'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCACHE 并指定每个连接上PSCACHE的大小，oracke为true，mysql为false 分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  redis:
    host: 47.102.217.76
    password: dhssd@hi!dd#
    port: 6382
    lettuce:
      pool:
        #最大等待时间
        max-wait: 1000ms
        #最大连接数
        max-active: 20
        #最大空闲数量
        max-idle: 20
        #最小空闲数
        min-idle: 1
      shutdown-timeout: 100ms
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        heart-beat-interval: 10
      config:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719
      eager: true
security:
  loginAfterTime: 10
  loginTimeLimit: 10
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cloud.wechat.movies.security.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.cloud.wechat.movies.security: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
#需要过滤的路径
ignored:
  urls:
  - /actuator/**
  - /login/**
  - /instances/**
